name: secure_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hive_ce: ^2.10.1
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.1
  equatable: ^2.0.7
  #flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  

flutter:
  uses-material-design: true
